### ISSUE TITLE
cant send multipart message

### ISSUE THREAD

**Issue by khaf0** [PavelBansky/SharpSMS#1]
hello,
i cant send multipart message,more than 1 message ,on last message i cant get +CMGS on modem response,
last message part is more than 154 byte.
please check.

-----------------code#--------------
            TextMessage textMessage = new TextMessage();
            textMessage.Text = "شششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششششش";
            textMessage.DataEncoding = DataEncoding.UCS2_16bit;
            SMSSubmit sms = new SMSSubmit();
            sms.MessageToSend = textMessage;
            sms.PhoneNumber = "09876543210";
            sms.ValidityPeriod = new TimeSpan(5, 0, 0, 0);
            List<byte[]> messageList = sms.GetPDUList();
            foreach (byte[] messagePart in messageList)
            {
                string message = BytesToHexString(messagePart);
                SendSmS(message, messagePart.Length - 1);
}
![multipart](https://cloud.githubusercontent.com/assets/11761492/6952853/ac0419d8-d8da-11e4-9eda-913f918ade32.png)

**Comment by PavelBansky** [comment]
Hi,
thanks for the repro. This looks like a bug. I've never used UCS2_16bit encoding, I guess that is what is causing the splitting algorithm to go bananas. I'll look at it over the weekend.
Thanks,
Pavel
