### ISSUE TITLE
how to use internet gateway (e.g. nowsms)?

### ISSUE THREAD

**Issue by daniel-bluesea** [PavelBansky/SharpSMS#2]

**Comment by PavelBansky** [comment]
Seems like nowsms does NOT support sending messages in PDU format. You would have to find gateway that has API that accepts PDU formatted messages.

http://support.nowsms.com/discus/messages/1/19757.html

**Comment by daniel-bluesea** [comment]
yes, but they have a modem app that generated the pdu and uses htc sendRawPdu api, and sends this pdu via the htc device modem, see http://www.nowsms.com/send-wap-push-and-binary-sms-with-android-phone-as-modem

**Comment by PavelBansky** [comment]
I never used this new feature of SMSnow, but as long as they support PDU - you are good to go with SharpSMS
