### ISSUE TITLE
I I wish you continued further development of the following features

### ISSUE THREAD

**Issue by ghost** [PavelBansky/SharpSMS#6]
- new SMS message alert
- read PDU and text SMS
- GSM 7-bit alphabet and UCS2 support
- concatenated (long) SMS support
- delete SMS

**Comment by PavelBansky** [comment]
Hi,

this library is meant for creating SMS messages, not to communicate with GSM modem (reading, alerts, deleting)
I 7-bit encoding and UCS2 is supported for creating new messages, same goes for concatenated messages.
